#+title: frame-workflow.el: Per-Frame Workflow on Emacs

[[https://travis-ci.org/akirak/frame-workflow.svg?branch=master]]

=Frame-workflow.el= lets you define and organize per-frame workflow for Emacs. This is yet another workspace solution such as eyebrowse, perspective, and framegroups. It is frame-oriented and supports frame-specific states and actions. It is also designed to integrate with [[https://github.com/alphapapa/frame-purpose.el][frame-purpose.el]] which lets you focus on particular things inside a frame.

* Installation
This package requires Emacs 25.1.

The package is not available on MELPA at present, but it may be added in the future. Clone the repository and add the directory to =load-path=.

It depends on the following packages. You have to install them as well:

- [[https://github.com/magnars/dash.el][dash.el]]
- [[https://github.com/alphapapa/frame-purpose.el][frame-purpose.el]] if you use an integration with the package

* Configuration
1. Load =frame-workflow.el=
2. Turn on =frame-workflow-mode=

** Subjects (or workspaces)
A /subject/ is a type of frame in frame-workflow. You can create one frame or multiple frames for a subject.

To define a subject, use =frame-workflow-define-subject=:

#+BEGIN_SRC emacs-lisp
  (frame-workflow-define-subject "emacs-lisp")
#+END_SRC

Every frame subject requires a name, which is a string to uniquely identify the subject.

** Keybindings
=frame-workflow-switch-frame= is a function that lets you switch to a frame for a given subject. You can use it to bind a key to switch to a particular workspace:

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "s-g e")
                  (lambda () (interactive) (frame-workflow-switch-frame "emacs-lisp")))
#+END_SRC

It is also a command that lets you select a subject via =completing-read=:

#+BEGIN_SRC emacs-lisp
  (global-set-key "s-s" 'frame-workflow-switch-frame)
#+END_SRC
* Usage
You can use the following commands to switch the context:

- =frame-workflow-make-frame=, which creates a new frame of a given subject.
- =frame-workflow-select-frame=, which selects an existing frame of a given subject.
- =frame-workflow-switch-frame=, which selects an existing frame of a given subject if there is one. Otherwise, it creates a new frame.

|                               | Select a frame | Create a frame |
|-------------------------------+----------------+----------------|
| =frame-workflow-make-frame=   | No             | Yes            |
| =frame-workflow-select-frame= | Yes            | No             |
| =frame-workflow-switch-frame= | Yes            | Yes            |
* Contribution
Any comments and patches on this package are welcome. Create a ticket or a pull request on GitHub.
* License
GPL v3
